# --------------
# -- Settings --
# --------------

title: Lisa Ferosa Ahmed
headline: >-
  Aspiring Data Analyst 
baseurl: ""
url: "https://lisa-ferosa.me"

# Compressed with TinyPNG
images:
  favicon: "/images/favicon.ico"
  hero: "/images/profile.png"

about:
  - >
      Experienced in teaching secondary education, lesson planning, collaborating with 
      a team, and differentiating instructions that best fit my students’ needs to succeed. 
      Currently a motivated and driven Educator with more than 2 years of experience working 
      with students in a school setting. Dedicated to promoting the development and growth 
      of all students and colleagues. Planning to move forward with broadening my experience 
      in different fields such as Business and Technology, whether it is related to education 
      or everyday&nbsp;life.

featured:
  - title: "COOP Fellowship Capstone Project"
    images: 
      - "/images/capstone/capstone1.png"
      - "/images/capstone/capstone2.png"
      - "/images/capstone/capstone3.png"
      - "/images/capstone/capstone4.png"
    text: >
      Collaborated with teams of 4 to 16 members to collect, clean, and analyze marketing performance data for a
      telecommunications client, driving data-informed decision&#8209;making.
      
      * Analyzed a dataset of ~13,000 cells to uncover patterns and answer business questions related to creative asset
      performance, utilizing statistical and exploratory data analysis&nbsp;techniques.
      
      * Generated actionable insights on ad size and messaging effectiveness across demographic segments by leveraging
      Tableau for data visualization and Excel (PivotTables, VLOOKUP) for in-depth data&nbsp;manipulation.

work:
  - company: "Fusion Academy"
    role: "Teacher/Mentor"
    years: "2023-Present"
    description: >
      * Developed ~30 data-driven lesson plans for 1:1 teaching in secondary education Humanities courses, using
        pedagogical approaches to construct instructional&nbsp;strategies.

      * Supported students with various learning disabilities, such as ADD, ODD, Autism,&nbsp;etc.

      * Identified learning obstacles and tailored individualized interventions, optimizing study techniques and retention
        strategies based on data&nbsp;insights.

      * Improved student performance by 40% by utilizing personalized instruction for 14&nbsp;students.

  - company: "The Child Center of New York"
    role: "Group Leader"
    years: "2021-2023"
    description: >
      * Effectively led after-school classrooms with 20 students at a time in 3rd grade while providing an inclusive and
      welcoming environment for all program students in collaboration with 12 fellow group&nbsp;leaders.
      
      * Leveraged teaching skills in communication, presentations, and subject expertise to assist students with homework by
      creating activities and lesson plans to support their daily&nbsp;curriculum.
      
      * Orchestrated and assessed student progress to identify opportunities to enhance tutoring methods by 30% while
      helping students achieve academic&nbsp;goals.

education:
  - link: "https://coopcareers.org/"
    image: "/images/coop.png"
    name: "COOP Careers"
    info: >
     <b>Data Analytics Fellow</b><br>
      Engaged in a highly selective 16-week fellowship program, acquiring expertise in data cleaning, transformation, analysis, and
      visualization using Excel, SQL, and Tableau, alongside continuous professional&nbsp;development.<br>
      200 hours of instruction time with a hands-on mastery of data tools, communication training, networking, and client
      work with actual&nbsp;companies.<br>
      June 2025<br>
      
  - link: "https://www.ccny.cuny.edu/"
    image: "/images/ccny.png"
    name: "CUNY The City College of New York"
    info: >
      <b>Bachelor of Arts in&nbsp;History</b><br>
      Minor in Secondary Education for Social&nbsp;Studies<br>
      August 2022<br>

certification:
  - name: "Google Data Analytics Specialization"
    link: "https://www.coursera.org/account/accomplishments/specialization/0MVA3GL9WT5X"

footer:
  - name: "GitHub"
    link: "https://github.com/lisa-ferosa"

  - name: "LinkedIn"
    link: "https://www.linkedin.com/in/lisa-ahmed"

  - name: "Resume"
    link: "/assets/Lisa.Ahmed.Resume.pdf"

  # - name: "Other Links"
  #   link: "other links here"

# Build settings
theme: minima

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
